version: "3.2"

services:
  cub_sign_in_app:
    restart: always
    build: ./app
    ports:
      - "8000:8000"
    command: >
      gunicorn
          --workers 1
          --access-logfile -
          --log-level warn
          --bind :8000
          app:app
    env_file: ./app/.env
    environment:
      - CUB_SIGN_IN_CONFIG=.env
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    links:
      - redis
      - celery
    volumes:
      - datavolume:/data
    labels:
      - traefik.enable=true
      - traefik.backend=flask
      - traefik.frontend.rule=${TRAEFIK_FRONTEND_RULE}

  redis:
    restart: always
    image: "redis"
    # command: "redis-server"
    ports:
      - "6379:6379"

  celery:
    restart: always
    build: ./app
    # Celery complains about being root but as 'nobody' we cannot
    # write files.
    # user: nobody
    command: >
      celery worker
          --loglevel=WARN
          --app app.celery
    env_file: ./app/.env
    environment:
      - CUB_SIGN_IN_CONFIG=.env
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    links:
      - redis
    volumes:
      - datavolume:/data

  traefix:
    image: traefik:1.5.4
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
        #    networks:
        #      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/acme:/etc/traefik/acme.json
    
volumes:
  datavolume:

          #networks:
          #  web:
          #    external: true
